# Generated by Django 6.1 on 2026-09-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('popular', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('activities', models.JSONField(blank=True, default=list)),
                ('safety_info', models.TextField(blank=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country'], name='destination_country_2ade19_idx'), models.Index(fields=['popular'], name='destination_popular_08bdd5_idx')],
            },
        ),
    ]
