# Generated by Django 6.1 on 2026-09-06 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_members', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('full', 'Full'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='destinations.destination')),
            ],
            options={
                'ordering': ['start_date', '-created_at'],
                'indexes': [models.Index(fields=['destination'], name='trips_trip_destina_427850_idx'), models.Index(fields=['creator'], name='trips_trip_creator_a4fead_idx'), models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'), models.Index(fields=['start_date'], name='trips_trip_start_d_d83967_idx')],
            },
        ),
    ]
